apiVersion: v2
name: egokey
version: 4.18.0-egokey.0
appVersion: 4.18.0-egokey.0
description: EgoKey preview chart. Do not use this chart for production deployments.
home: https://github.com/anxrch/egokey
sources:
  - https://github.com/anxrch/egokey
