services:
  web:
    image: node:22.15.0-bookworm
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
      - "5173:5173"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      bash -c "corepack enable && pnpm install --frozen-lockfile && pnpm dev"
    environment:
      - NODE_ENV=development

  redis:
    restart: always
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: always
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

volumes:
  node_modules:
