packages:
  - packages/backend
  - packages/frontend-shared
  - packages/frontend
  - packages/frontend-builder
  - packages/frontend-embed
  - packages/i18n
  - packages/icons-subsetter
  - packages/sw
  - packages/cherrypick-js
  - packages/cherrypick-js/generator
  - packages/misskey-reversi
  - packages/misskey-bubble-game
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@sentry/profiling-node'
  - '@sentry-internal/node-cpu-profiler'
  - '@swc/core'
  - '@tensorflow/tfjs-node'
  - argon2
  - bufferutil
  - canvas
  - core-js
  - cypress
  - esbuild
  - msgpackr-extract
  - msw
  - nice-napi
  - protobufjs
  - re2
  - sharp
  - utf-8-validate
  - v-code-diff
  - vue-demi
ignorePatchFailures: false
minimumReleaseAge: 10080 # delay 7days to mitigate supply-chain attack
minimumReleaseAgeExclude:
  - '@syuilo/aiscript'
  - systeminformation # 脆弱性対応。そのうち消すこと
  - 'mfc-js'
