contact_links:
  - name: 💬 Misskey official Discord
    url: https://discord.gg/Wp8gVStHW3
    about: Chat freely about Misskey
  # 仮
  - name: 💬 Start discussion (Misskey)
    url: https://github.com/misskey-dev/misskey/discussions
    about: The official forum to join conversation and ask question
  - name: 💬 Start an EgoKey discussion
    url: https://github.com/anxrch/egokey/discussions
    about: The official forum to join conversation and ask question
